
name: Greetings

on:
  issues:
    types: [closed]
  pull_request:
    types: [closed]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: Manoj-Paramsetti/Greeting-action@main
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        issue_message: 'Thank you for all the participants! For taking out your time to raise an issue.<br>This issue is closed by @${{github.actor + github.actor}}'
        PR_message: 'Thank you @${{github.actor}} for taking out your time and contributing to our project.'
